# Generated by Django 2.2 on 2019-04-14 14:54

import django-bcf-manager.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkupHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_creation', models.DateTimeField(auto_now_add=True)),
                ('dt_modification', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(django-bcf-manager.models.ValidateModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('extension_schema', models.CharField(max_length=255)),
                ('dt_creation', models.DateTimeField(auto_now_add=True)),
                ('dt_modification', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(django-bcf-manager.models.ValidateModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=255)),
                ('topic_type', models.CharField(max_length=255)),
                ('topic_status', models.CharField(max_length=255)),
                ('dt_creation', models.DateTimeField(auto_now_add=True)),
                ('dt_modification', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django-bcf-manager.Project')),
            ],
            bases=(django-bcf-manager.models.ValidateModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TopicLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=255)),
            ],
            bases=(django-bcf-manager.models.ValidateModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TopicPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=255)),
            ],
            bases=(django-bcf-manager.models.ValidateModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TopicReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
            ],
            bases=(django-bcf-manager.models.ValidateModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TopicStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=255)),
            ],
            bases=(django-bcf-manager.models.ValidateModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TopicNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('creation_date', models.DateTimeField()),
                ('creation_author', models.CharField(max_length=255)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('modified_author', models.CharField(blank=True, max_length=255, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
                ('labels', models.ManyToManyField(to='django-bcf-manager.TopicLabel')),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django-bcf-manager.TopicPriority')),
                ('reference_link', models.ManyToManyField(to='django-bcf-manager.TopicReference')),
                ('stage', models.ManyToManyField(to='django-bcf-manager.TopicStage')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django-bcf-manager.Topic')),
            ],
            bases=(django-bcf-manager.models.ValidateModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MarkupHeaderFilenode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifc_project', models.CharField(blank=True, max_length=255, null=True)),
                ('ifc_spatial_structure_element', models.CharField(blank=True, max_length=255, null=True)),
                ('is_external', models.BooleanField(default=True)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('dt_creation', models.DateTimeField(auto_now_add=True)),
                ('dt_modification', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('markup_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django-bcf-manager.MarkupHeader')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(django-bcf-manager.models.ValidateModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='markupheader',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django-bcf-manager.Project'),
        ),
    ]
