# Generated by Django 3.1.2 on 2021-02-01 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_bcf_manager.models.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_creation', models.DateTimeField(auto_now_add=True)),
                ('dt_modification', models.DateTimeField(auto_now=True)),
                ('project_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, null=True)),
                ('extension_schema', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_date', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_author', models.CharField(blank=True, max_length=255)),
                ('modified_date', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_author', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', django_bcf_manager.models.base.CustomUserCreatedFk(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='Project_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', django_bcf_manager.models.base.CustomUserModifiedFk(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='Project_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopicStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_creation', models.DateTimeField(auto_now_add=True)),
                ('dt_modification', models.DateTimeField(auto_now=True)),
                ('priority', models.CharField(max_length=255)),
                ('created_by', django_bcf_manager.models.base.CustomUserCreatedFk(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='Topic_Stage_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', django_bcf_manager.models.base.CustomUserModifiedFk(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='Topic_Stage_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopicReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_creation', models.DateTimeField(auto_now_add=True)),
                ('dt_modification', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=255)),
                ('created_by', django_bcf_manager.models.base.CustomUserCreatedFk(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='Topic_Reference_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', django_bcf_manager.models.base.CustomUserModifiedFk(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='Topic_Reference_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopicPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_creation', models.DateTimeField(auto_now_add=True)),
                ('dt_modification', models.DateTimeField(auto_now=True)),
                ('priority', models.CharField(max_length=255)),
                ('created_by', django_bcf_manager.models.base.CustomUserCreatedFk(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='Topic_Priority_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', django_bcf_manager.models.base.CustomUserModifiedFk(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='Topic_Priority_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopicLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_creation', models.DateTimeField(auto_now_add=True)),
                ('dt_modification', models.DateTimeField(auto_now=True)),
                ('priority', models.CharField(max_length=255)),
                ('created_by', django_bcf_manager.models.base.CustomUserCreatedFk(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='Topic_Label_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', django_bcf_manager.models.base.CustomUserModifiedFk(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='Topic_Label_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_creation', models.DateTimeField(auto_now_add=True)),
                ('dt_modification', models.DateTimeField(auto_now=True)),
                ('guid', models.CharField(max_length=255)),
                ('topic_type', models.CharField(blank=True, max_length=255, null=True)),
                ('topic_status', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('creation_date', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_author', models.CharField(blank=True, max_length=255)),
                ('modified_date', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_author', models.CharField(blank=True, max_length=255, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
                ('created_by', django_bcf_manager.models.base.CustomUserCreatedFk(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='Topic_creator', to=settings.AUTH_USER_MODEL)),
                ('labels', models.ManyToManyField(to='django_bcf_manager.TopicLabel')),
                ('modified_by', django_bcf_manager.models.base.CustomUserModifiedFk(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='Topic_modifier', to=settings.AUTH_USER_MODEL)),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_bcf_manager.topicpriority')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_bcf_manager.project')),
                ('reference_link', models.ManyToManyField(to='django_bcf_manager.TopicReference')),
                ('stage', models.ManyToManyField(to='django_bcf_manager.TopicStage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarkupHeaderFilenode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifc_project', models.CharField(blank=True, max_length=255, null=True)),
                ('ifc_spatial_structure_element', models.CharField(blank=True, max_length=255, null=True)),
                ('is_external', models.BooleanField(default=True)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('dt_creation', models.DateTimeField(auto_now_add=True)),
                ('dt_modification', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_bcf_manager.topic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BcfFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_creation', models.DateTimeField(auto_now_add=True)),
                ('dt_modification', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='bcf')),
                ('created_by', django_bcf_manager.models.base.CustomUserCreatedFk(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='Bcf_File_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', django_bcf_manager.models.base.CustomUserModifiedFk(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='Bcf_File_modifier', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_bcf_manager.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
