# Generated by Django 2.2 on 2019-04-15 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_bcf_manager.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_bcf_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BcfFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='bcf')),
                ('dt_creation', models.DateTimeField(auto_now_add=True)),
                ('dt_modification', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_bcf_manager.Project')),
            ],
            bases=(django_bcf_manager.models.ModelMixin, models.Model),
        ),
    ]
