# Generated by Django 2.2 on 2019-04-15 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_bcf_manager', '0002_bcffiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='sourcefile',
        ),
        migrations.AlterField(
            model_name='bcffiles',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bcffiles',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_bcf_manager.Project'),
        ),
    ]
