# Generated by Django 2.2 on 2019-04-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bcf_manager', '0003_auto_20190415_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sourcefile',
            field=models.CharField(default='', max_length=255),
        ),
    ]
