# Generated by Django 2.2 on 2019-04-16 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_bcf_manager.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_bcf_manager', '0004_project_sourcefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BcfFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='bcf')),
                ('dt_creation', models.DateTimeField(auto_now_add=True)),
                ('dt_modification', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(django_bcf_manager.models.ModelMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='project',
            name='sourcefile',
        ),
        migrations.DeleteModel(
            name='BcfFiles',
        ),
        migrations.AddField(
            model_name='project',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_bcf_manager.BcfFile'),
        ),
    ]
