# Generated by Django 2.2 on 2019-04-16 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_bcf_manager', '0006_auto_20190416_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bcffile',
            name='dt_modification',
        ),
        migrations.RemoveField(
            model_name='bcffile',
            name='modified_by',
        ),
    ]
