# Generated by Django 2.2 on 2019-04-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bcf_manager', '0007_auto_20190416_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='creation_author',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
